CREATE TABLE employee(
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,
    department VARCHAR(50),
    email_address VARCHAR(50), 
    phone_number VARCHAR(50)
);