# Tipo de base de datos (por ejemplo, PostgreSQL, MySQL, H2, etc.)
quarkus.datasource.db-kind=postgresql

# URL de conexión JDBC
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/employees_db

# Usuario y contraseña
quarkus.datasource.username=user
quarkus.datasource.password=password
