quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=usuario
quarkus.datasource.password=pass
quarkus.datasource.reactive.url=postgresql://localhost:5432/employees_db

quarkus.datasource.jdbc=false
quarkus.hibernate-orm.database.generation=drop-and-create