quarkus:
  banner:
    enabled: false
  datasource:
    db-kind: postgresql
    username: fox
    password: F0xF1r3
    jdbc:
      url: jdbc:postgresql://localhost:5432/employees_db
    devservices:
      enabled: false  # Deshabilitamos devservices ya que tenemos BD externa
  flyway:
    migrate-at-start: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-on-validation-error: true  # Solo en desarrollo
  hibernate-orm:
    database:
      generation: none

"%dev":
  quarkus:
    log:
      level: INFO
      category:
        "dev.damian":
          level: DEBUG
    hibernate-orm:
      log:
        sql: true

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: Employee API
          version: 0.0.1
          description: REST API for employees data
