# --- Reactive Datasource Configuration ---
# We use the reactive url for Hibernate Reactive
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=fox
quarkus.datasource.password=F0xF1r3
quarkus.datasource.reactive.url=postgresql://localhost:5432/employees_db

# We disable the JDBC driver since we are fully reactive
quarkus.datasource.jdbc.enabled=false
